title: Welcome to my page!
description: A civil engineer with purpose passionate about creating
![Glacier background](Glacier background.JPG)
avatar: https://avatars1.githubusercontent.com/u/32068319?v=4&s=400&u=079a359b9c35a61da74234cc545e285a5e9b21c0
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
