---
theme: jekyll-theme-minimal
title: Welcome to my page!
description: An engineer with a purpose
jekyll-avatar: https://github.com/KhanyaBouma/khanyabouma.github.io/blob/master/Edited%20Khanya%20Bouma.png

dribbble:
  email: khanya.bouma@gmail.com
  instagram: lightofkhanya
  linkedin: https://www.linkedin.com/in/khanya-bouma-6653158b/
  pinterest: www.pinterest.com/khanyabouma
---
