---
theme: jekyll-theme-minimal
title: Welcome to my page!
description: An engineer with a purpose
group: jekyll_plugins
jekyll-avatar: https://github.com/KhanyaBouma/khanyabouma.github.io/blob/master/Edited%20Khanya%20Bouma.png

<script: "//platform.linkedin.com/in.js" type="text/javascript"></script>
<script type: "IN/MemberProfile" data-id="https://www.linkedin.com/in/khanya-bouma-6653158b" data-format="click" data-related="false"></script>
---
