theme: jekyll-theme-minimal
title: Welcome to my page!
description: An engineer with a purpose

avatar: Khanya Bouma Profile/Edited Khanya Bouma.png

dribbble:
  email: khanya.bouma@gmail.com
  instagram: lightofkhanya
  linkedin: https://www.linkedin.com/in/khanya-bouma-6653158b/
  pinterest: www.pinterest.com/khanyabouma
  
